POST http://localhost:8080/api/payments
Authorization: bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "200 PLN"
}

###

GET http://localhost:8080/api/payments/e2ce6390-d4b6-4744-9e50-20ab28d17535
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/payments/started?pageNumer=0
Authorization: bearer {{token}}
Accept: application/json
Content-Type: application/json

###

//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=shop-client&grant_type=password&username=client&password=123

> {%
    client.global.set('token', response.body.access_token);
    client.global.set('refreshToken', response.body.refresh_token);
%}

###

//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/training/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=shop-client&grant_type=refresh_token&refresh_token={{ refreshToken }}

> {%
    client.global.set('token', response.body.access_token);
    client.global.set('refreshToken', response.body.refresh_token);
%}

###

//@no-redirect
//@no-cookie-jar
POST http://localhost:8100/realms/training/protocol/openid-connect/revoke
Content-Type: application/x-www-form-urlencoded

client_id=shop-client&grant_type=password&username=client&password=123&token={{ token }}

