version: '3'
services:
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    command:
      - start-dev
    ports:
      - "8100:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: "POSTGRES"
      DB_ADDR: "database"
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      DB_DATABASE: "shop"
