spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    #hibernate:
    #  ddl-auto: create-drop
    open-in-view: false
  messages:
    basename: exceptions,text
  profiles:
    active: development
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8100/realms/training
      client:
        registration:
          keycloak:
            client-id: shop-client
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8100/realms/training

logging:
  level:
    org.javamoney.moneta: OFF
