spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:file:./data/payments.db
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  messages:
    basename: exceptions
